import { BusinessType } from './types';

export const BUSINESSES: BusinessType[] = [
  {
    id: 'cafe',
    label: 'Café & Coffee',
    emoji: '☕',
    accent: '#D4956A',
    light: '#F2C49E',
    darkBg: '#1a0d05',
    tone: 'warm cozy artisanal',
    layout: 'split',
    exampleOffer: 'Buy 1 Get 1 Free on all cold coffees today!',
  },
  {
    id: 'restaurant',
    label: 'Restaurant',
    emoji: '🍽️',
    accent: '#E07060',
    light: '#F5A898',
    darkBg: '#1a0800',
    tone: 'appetizing bold',
    layout: 'centered',
    exampleOffer: 'Family Feast for 4 at just ₹999 this weekend!',
  },
  {
    id: 'gym',
    label: 'Gym & Fitness',
    emoji: '💪',
    accent: '#FFD600',
    light: '#FFE94D',
    darkBg: '#0a0a00',
    tone: 'powerful motivational',
    layout: 'bold',
    exampleOffer: 'Join now — First month FREE! No registration fee.',
  },
  {
    id: 'salon',
    label: 'Salon & Spa',
    emoji: '💇',
    accent: '#C9A84C',
    light: '#E8C97A',
    darkBg: '#0d0a00',
    tone: 'elegant luxurious',
    layout: 'premium',
    exampleOffer: 'Full bridal package at 30% off — Book this week!',
  },
  {
    id: 'clinic',
    label: 'Clinic & Pharmacy',
    emoji: '🏥',
    accent: '#4FC3F7',
    light: '#B3E5FC',
    darkBg: '#00080f',
    tone: 'trustworthy caring',
    layout: 'clean',
    exampleOffer: 'Free health checkup this Saturday — Walk in welcome',
  },
  {
    id: 'coaching',
    label: 'Coaching & Tuition',
    emoji: '🏫',
    accent: '#AB47BC',
    light: '#CE93D8',
    darkBg: '#0d0010',
    tone: 'motivational results-driven',
    layout: 'bold',
    exampleOffer: 'Enroll now — Free demo class + study materials',
  },
  {
    id: 'retail',
    label: 'Retail & Shop',
    emoji: '🛍️',
    accent: '#00E676',
    light: '#69F0AE',
    darkBg: '#00100a',
    tone: 'exciting promotional',
    layout: 'promo',
    exampleOffer: 'FLAT 50% OFF on all items — Today only!',
  },
  {
    id: 'realestate',
    label: 'Real Estate',
    emoji: '🏠',
    accent: '#E8C97A',
    light: '#F5E2A8',
    darkBg: '#0d0a00',
    tone: 'prestigious aspirational',
    layout: 'premium',
    exampleOffer: '2BHK flats starting ₹25L — Limited units left',
  },
  {
    id: 'hotel',
    label: 'Hotel & Homestay',
    emoji: '🏨',
    accent: '#F39C12',
    light: '#F9C74F',
    darkBg: '#0f0800',
    tone: 'welcoming comfortable',
    layout: 'premium',
    exampleOffer: 'Weekend stay + Breakfast at ₹1999 only!',
  },
  {
    id: 'bakery',
    label: 'Bakery & Sweets',
    emoji: '🎂',
    accent: '#E91E8C',
    light: '#F48FB1',
    darkBg: '#1a0010',
    tone: 'sweet celebratory',
    layout: 'promo',
    exampleOffer: 'Custom birthday cakes from ₹499 — Order 24hrs ahead',
  },
  {
    id: 'fashion',
    label: 'Fashion & Clothing',
    emoji: '👗',
    accent: '#9C27B0',
    light: '#CE93D8',
    darkBg: '#0d0010',
    tone: 'trendy stylish',
    layout: 'premium',
    exampleOffer: 'New collection arrived — Up to 40% off on all ethnic wear',
  },
  {
    id: 'electronics',
    label: 'Electronics & Repair',
    emoji: '📱',
    accent: '#00BCD4',
    light: '#80DEEA',
    darkBg: '#00080f',
    tone: 'technical reliable',
    layout: 'clean',
    exampleOffer: 'Phone screen repair in 30 mins — ₹299 flat rate',
  },
  {
    id: 'travel',
    label: 'Travel & Tours',
    emoji: '✈️',
    accent: '#03A9F4',
    light: '#81D4FA',
    darkBg: '#00060f',
    tone: 'adventurous exciting',
    layout: 'centered',
    exampleOffer: 'Kerala backwaters 3D/2N package from ₹4999/person',
  },
  {
    id: 'auto',
    label: 'Auto & Car Service',
    emoji: '🚗',
    accent: '#FF5722',
    light: '#FF8A65',
    darkBg: '#0f0300',
    tone: 'reliable trusted',
    layout: 'bold',
    exampleOffer: 'Full car service + AC check at ₹799 only!',
  },
  {
    id: 'education',
    label: 'School & College',
    emoji: '📚',
    accent: '#90CAF9',
    light: '#BBDEFB',
    darkBg: '#000a18',
    tone: 'inspiring academic',
    layout: 'clean',
    exampleOffer: 'Admissions open 2024 — Early bird scholarship available',
  },
  {
    id: 'event',
    label: 'Events & Wedding',
    emoji: '🎉',
    accent: '#FF4081',
    light: '#FF80AB',
    darkBg: '#1a0010',
    tone: 'celebratory emotional',
    layout: 'premium',
    exampleOffer: 'Complete wedding decor packages from ₹15,000',
  },
  {
    id: 'interior',
    label: 'Interior & Furniture',
    emoji: '🏡',
    accent: '#A1887F',
    light: '#D7CCC8',
    darkBg: '#0d0805',
    tone: 'sophisticated homely',
    layout: 'premium',
    exampleOffer: 'Full home interior in 30 days — Free 3D design consultation',
  },
  {
    id: 'pharmacy',
    label: 'Pharmacy & Wellness',
    emoji: '💊',
    accent: '#4CAF50',
    light: '#A5D6A7',
    darkBg: '#000f02',
    tone: 'caring health-focused',
    layout: 'clean',
    exampleOffer: '10% off on all medicines + Free home delivery above ₹500',
  },
  {
    id: 'yoga',
    label: 'Yoga & Wellness',
    emoji: '🧘',
    accent: '#FF9800',
    light: '#FFCC80',
    darkBg: '#0f0600',
    tone: 'peaceful holistic',
    layout: 'centered',
    exampleOffer: '21-day transformation program — Join this Monday',
  },
  {
    id: 'photography',
    label: 'Photography Studio',
    emoji: '📷',
    accent: '#90A4AE',
    light: '#CFD8DC',
    darkBg: '#050a0d',
    tone: 'creative artistic',
    layout: 'premium',
    exampleOffer: 'Pre-wedding shoot package at ₹2999 — 100 edited photos',
  },
];

export function getBusiness(id: string): BusinessType {
  return BUSINESSES.find((b) => b.id === id) || BUSINESSES[0];
}
